# Generated by Django 5.2.7 on 2025-10-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MotoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="moto_images/")),
            ],
            options={
                "verbose_name": "Moto Image",
                "verbose_name_plural": "Moto Images",
            },
        ),
    ]
